"""initial schema: meetings and segments

Revision ID: 43864c289d53
Revises: 
Create Date: 2026-09-02 02:30:41.310560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43864c289d53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'transcribing', 'transcribed', 'segmented', 'ready', 'failed', name='meetingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('meeting_id')
    )
    op.create_index(op.f('ix_meetings_meeting_id'), 'meetings', ['meeting_id'], unique=False)
    op.create_table('segments',
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('decision_text', sa.Text(), nullable=True),
    sa.Column('segment_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.meeting_id'], ),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.create_index(op.f('ix_segments_meeting_id'), 'segments', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_segments_segment_id'), 'segments', ['segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segments_segment_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_meeting_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_meetings_meeting_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###